import Link from "next/link";

import { LandingNavigation } from "@/components/layout/landing-navigation";

const sections = [
  {
    title: "1. Acceptance of Terms",
    body: "By accessing or using Vessel, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree, do not use the platform.",
  },
  {
    title: "2. Eligibility",
    body: "You must be legally capable of entering into binding agreements in your jurisdiction. You are responsible for ensuring your use of Vessel is lawful where you reside.",
  },
  {
    title: "3. Wallet and Identity",
    body: "Vessel relies on your Solana wallet as your primary identity and authorization mechanism. You are solely responsible for safeguarding wallet credentials, private keys, and approvals.",
  },
  {
    title: "4. Agent Execution and Risk",
    body: "Agents may execute blockchain actions based on configured policies and tool permissions. You are solely responsible for your agent configuration, execution outcomes, transaction costs, and any resulting gains or losses.",
  },
  {
    title: "5. No Financial Advice",
    body: "Vessel, its interfaces, and any outputs generated by agents are provided for software orchestration purposes only and do not constitute financial, investment, legal, or tax advice.",
  },
  {
    title: "6. Marketplace Listings",
    body: "If you list, rent, or purchase agents through marketplace features, you are responsible for verifying listing details, pricing, and suitability. Vessel may provide technical rails but is not a party to your bilateral transaction terms.",
  },
  {
    title: "7. Fees and Network Costs",
    body: "You are responsible for all applicable blockchain network fees, gas costs, slippage, and third-party service fees associated with actions initiated through Vessel.",
  },
  {
    title: "8. Acceptable Use",
    body: "You may not use Vessel for unlawful conduct, sanctions evasion, fraud, abuse, exploitation of vulnerabilities, or activities that impair platform security or availability.",
  },
  {
    title: "9. Intellectual Property",
    body: "All trademarks, logos, and platform materials are owned by Vessel or its licensors. You retain ownership of your own prompts, configuration data, and content, subject to rights needed to operate the service.",
  },
  {
    title: "10. Third-Party Services",
    body: "Vessel may integrate with third-party tools, APIs, RPC providers, wallets, and protocols. Vessel is not responsible for third-party availability, terms, outages, or losses caused by third-party systems.",
  },
  {
    title: "11. Service Availability",
    body: "The service is provided on an " + '"as is"' + " and " + '"as available"' + " basis. We may modify, suspend, or discontinue functionality at any time, including alpha and beta features.",
  },
  {
    title: "12. Limitation of Liability",
    body: "To the maximum extent permitted by law, Vessel and its affiliates are not liable for indirect, incidental, consequential, special, or punitive damages, including loss of funds, profits, data, or opportunity.",
  },
  {
    title: "13. Indemnification",
    body: "You agree to indemnify and hold harmless Vessel and its affiliates from claims, liabilities, damages, and expenses arising from your use of the platform or violation of these terms.",
  },
  {
    title: "14. Governing Law",
    body: "These Terms are governed by applicable laws in the jurisdiction designated by Vessel. Dispute resolution venue and procedure may be specified by separate notice.",
  },
  {
    title: "15. Changes to Terms",
    body: "We may update these Terms periodically. Continued use after changes become effective constitutes acceptance of the revised Terms.",
  },
  {
    title: "16. Contact",
    body: "For legal inquiries, email: legal@vessel.engine",
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#f5f5f6] text-[#111112]">
      <LandingNavigation forceLight />

      <main className="mx-auto w-full max-w-[1100px] px-5 py-10 pt-24 sm:px-8 sm:py-12">
        <div className="rounded-xl border border-black/10 bg-white p-6 sm:p-10">
          <p className="text-[11px] font-semibold tracking-[0.14em] text-[#9e1422]">LEGAL</p>
          <h1 className="mt-2 text-[44px] font-semibold leading-[1.02] tracking-[-0.03em] text-black sm:text-[58px]">
            Terms of Service
          </h1>
          <p className="mt-3 text-[14px] text-black/65">Effective Date: April 4, 2026</p>
          <p className="mt-5 max-w-[780px] text-[16px] leading-relaxed text-black/75">
            These Terms of Service govern your access to and use of Vessel, including agent orchestration,
            policy-controlled execution, and marketplace interactions.
          </p>

          <div className="mt-8 space-y-5">
            {sections.map((section) => (
              <section key={section.title} className="rounded-lg border border-black/10 bg-white p-4 sm:p-5">
                <h2 className="text-[18px] font-semibold tracking-[-0.01em] text-black">{section.title}</h2>
                <p className="mt-2 text-[14px] leading-relaxed text-black/72">{section.body}</p>
              </section>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}
